###########################################
/My/PrimaryGenerator/select   GPS
/gps/particle e-
/gps/pos/type   Beam
/gps/pos/centre   0 0  1250. mm
/gps/pos/sigma_r   10.  mm
/gps/ang/type   beam2d
/gps/ang/sigma_x   0.003 rad
/gps/ang/sigma_y   0.003 rad
/gps/ang/rot1  1 0 0
/gps/ang/rot2  0 1 0
/gps/ene/type      Gauss
/gps/ene/mono      6.0 MeV
/gps/ene/sigma     0.127 MeV
###########################################
