#--------------------------------------------------------------------------------------
#
# Macro file is for Bragg peak distribution in water.
# The energies of proton are chosen to be 150 MeV, 190 MeV, and 230 MeV.
# All processes are included.
# Though measurements are done using small detector (radius ~ 5mm), this macro
# uses simple plate of 200. x 200. x 1. mm water. The plates are aligned to z-axis.
# 
#       2006 AUG. 30   Tsukasa ASO
#
#--------------------------------------------------------------------------------------
#
#  (PreInit State)
#
# -------------------------------------------------------------------------------------
# [OP]Verbose settings
# -------------------------------------------------------------------------------------
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
#
#======================================================================================
# [MA]Material
#======================================================================================
/control/execute ./macros/common/materials.mac
#
#======================================================================================
# [MA]PhysicsList
#======================================================================================
/control/execute ./macros/common/phys.mac
#
#======================================================================================
# [MA]Particle Therapy System Selection and Beam Module Registration
#======================================================================================
/G4M/System DynamicPort
/control/execute  ./macros/DynamicPort/beamModule.mac
#####
# EVENT DUMPER Module
/Dynamic/Module/register Dumper        G4MDiskDumper      ./data/Sample/G4MDiskDumper/dumper.dat         0. 0.  700. mm 0. 0. 0. deg
#####
#
#======================================================================================
# [MA]Run Initialize
#======================================================================================
/run/initialize
#
#
#  (Idle State)
#
#======================================================================================
# [MA]Beam Module Implmentation
#======================================================================================
/G4M/Module/list
# -----------------------------------------
# Water Phantom settings and installation
# ----------------------------------------- 
## Water Phantom Size (Half length)
/G4M/Module/Phantom/size 150. 150. 250.0 mm
## Water Phantom SD Size (Half length) 
/G4M/Module/Phantom/sdsize 150.0 150.0 250.0 mm
## Segmentation of water phantom ( Nx, Ny, Nz )
/G4M/Module/Phantom/dim 300. 300. 500.
## Installation of WaterPhantom. 
##/G4M/Module/install WaterPhantom
#
# -----------------------------------------
# Installation of the other modules
# ----------------------------------------- 
#/G4M/Module/install Extract
#/G4M/Module/install Scatter
#/G4M/Module/install WobblerX
#/G4M/Module/install WobblerY
#/G4M/Module/install MainMonitor
#/G4M/Module/install SECMonitor
#/G4M/Module/install FlatMonitor
#/G4M/Module/install Collimator
#/G4M/Module/install MLC
/G4M/Module/install Dumper
#
# -------------------------------------------------------------------------------------
# [OP] Change Beam Module Parameters
# -------------------------------------------------------------------------------------
/G4M/Module/select Dumper
#/G4M/Module/translate 0. 0. 200. mm
#
#======================================================================================
# [MA] Beam Parameters
#======================================================================================
/control/execute macros/DynamicPort/particleGun.mac
##/gun/particle neutron
##/gun/particle gamma
##/gun/particle e-
/gun/particle ion
/gun/ion 6 12 6
/gun/energy 3840 MeV
#
# -------------------------------------------------------------------------------------
# [OP] ROOT Output file Name
# -------------------------------------------------------------------------------------
/control/execute ./macros/common/Hist.mac
/My/runaction/dumpfile SampleEvtDumper.root
#
#======================================================================================
# [OP] Visualization Settings
#======================================================================================
#/control/execute ./macros/common/vis.mac
#
#======================================================================================
# [MA] BeamOn
#======================================================================================
#
####
# EVENT Interface File open
/G4M/DumpInfo/open trackDump.data
####
/run/beamOn 1000
####
# EVENT Interface File close
/G4M/DumpInfo/close
#
# --EOF----------------------------------------------------------------------------------
