/My/runaction/hist/enable DICOMCT false
/My/runaction/hist/enable DICOM   false
/My/runaction/hist/enable JSTEdep false
/My/runaction/hist/enable JSTDose true
#
/My/runaction/hist/enable JST     true
###/My/runaction/ntuple/create JST
/My/runaction/ntuple/addColumn JST evno I
/My/runaction/ntuple/addColumn JST pid I
/My/runaction/ntuple/addColumn JST de  F  keV
/My/runaction/ntuple/addColumn JST ix  I
/My/runaction/ntuple/addColumn JST iy  I
/My/runaction/ntuple/addColumn JST iz  I
###